# Generated by Django 5.2.4 on 2025-10-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user_email",
            field=models.EmailField(
                error_messages={
                    "invalid": "Enter a valid email address",
                    "required": "Email is required",
                },
                max_length=254,
            ),
        ),
    ]
